apiVersion: v1
kind: Service
metadata:
  name: nodePort-service
  labels: 
    type:  service
spec: 
  type: NodePort
  ports:  
    - targetPort: 80
      port: 80
      nodePort: 8080

  